version: "3"
services:
  postgres:
    image: mypostgres:latest
    network_mode: bridge
    expose:
    - 5432
    ports:
      - 5432:5432
    volumes:
         - pgdata:/var/lib/postgresql/data    
    environment:
         - POSTGRES_PASSWORD=password
         - POSTGRES_USER=postgres
         - POSTGRES_DB=testdb
    restart: unless-stopped

  springbootapp:
    image: springbootapp:latest
    network_mode: bridge
    expose:
      - 8080
    ports:
      - 8080:8080
    restart: unless-stopped
    depends_on:
      - postgres
    links:
      - postgres
volumes:
  pgdata: